### ISSUE TITLE
Accuracy of alternative pin uses for Raspberry Pi 4

### ISSUE THREAD

**Issue by rgov** [Gadgetoid/Pinout.xyz#377] opened 2020-09-14 17:49 UTC
The Raspberry Pi 4 introduced additional UARTs which can be enabled with the dtoverlays `uart2`, `uart3`, `uart4`, and `uart5` respectively. Enabling an overlay repurposes some GPIO pins for the TX/RX.

I have had a hard time finding documentation for which pins get used but my best source is [this table](https://github.com/RPi-Distro/raspi-gpio/blob/master/raspi-gpio.c#L99) in the sources of the `raspi-gpio` tool originally written by the then-Director of Hardware Engineering of the Raspberry Pi Foundation, so I take it to be a reputable source.

The table suggests that the pinouts for the BCM2711 used by the Raspberry Pi 4 differ from those of the BCM2708 used by other models. Here is the differences for GPIO 0 through 27, highlighted orange where they are not the same:

<img width="761" alt="image" src="https://user-images.githubusercontent.com/108767/93120231-0bfc5b00-f691-11ea-9b13-f3ddffb76a08.png">

It would be good to have this information presented on the site.

**Comment by lurch** [comment] 2020-09-15 08:31
Duplicate of #322 ?

**Comment by Gadgetoid** [comment] 2020-09-15 09:46
Either way it's clear I need to do something about this!

@rgov does the table view presented here https://github.com/Gadgetoid/Pinout.xyz/issues/322 with @lurch 's modifications work for you?

(Closing this to focus discussion on #322)

**Closed by Gadgetoid** 2020-09-15 09:46 UTC

**Comment by rgov** [comment] 2020-09-15 13:56
@lurch Thanks, fixed the diagram for posterity. @Gadgetoid The mockup you posted looks good, though I agree highlighting the differences would be good.
