### ISSUE TITLE
There's a tab for ground pins, but not for 3v3 or 5v

### ISSUE THREAD

**Issue by 2231puppy** [Gadgetoid/Pinout.xyz#360] opened 2020-03-30 17:49 UTC

**Comment by lurch** [comment] 2020-03-31 09:59
Duplicate of #314 ?

**Comment by 2231puppy** [comment] 2020-03-31 18:17
I guess it is. Sorry, didn't see that. I should have looked a bit deeper into the history.

**Comment by Gadgetoid** [comment] 2020-06-25 11:40
No worries, I'll close this in favour of the other. I'm long overdue a sprint on Pinout to sort out all sorts of quirks and bugs so hopefully I'll get this done in July.

**Closed by Gadgetoid** 2020-06-25 11:40 UTC
